#!/usr/bin/env bash
# ServerControl Agent Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/servercontrol/agent/main/install.sh | bash
# Or with a custom token: SC_TOKEN=mytoken bash install.sh

set -euo pipefail

AGENT_VERSION="${SC_AGENT_VERSION:-1.0.5}"
INSTALL_DIR="/usr/local/bin"
BINARY_NAME="servercontrol-agent"
CONFIG_DIR="/etc/servercontrol"
CONFIG_FILE="$CONFIG_DIR/agent.conf"
SERVICE_FILE="/etc/systemd/system/servercontrol.service"
GITHUB_REPO="aadithya96/ServerControl"
DEFAULT_PORT="9876"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# --- Preflight checks ---
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    log_error "This installer only supports Linux."
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    log_error "This installer must be run as root (use sudo)."
    exit 1
fi

# --- Detect architecture ---
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)   GOARCH="amd64" ;;
    aarch64)  GOARCH="arm64" ;;
    armv7l)   GOARCH="arm" ;;
    *)
        log_warn "Unknown architecture: $ARCH. Attempting to build from source."
        GOARCH=""
        ;;
esac

# --- Determine token ---
if [[ -z "${SC_TOKEN:-}" ]]; then
    # Check if already configured
    if [[ -f "$CONFIG_FILE" ]] && grep -q "^TOKEN=" "$CONFIG_FILE" 2>/dev/null; then
        SC_TOKEN=$(grep "^TOKEN=" "$CONFIG_FILE" | cut -d= -f2-)
        log_info "Reusing existing token from $CONFIG_FILE"
    else
        # Generate random token
        SC_TOKEN=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 48 | head -n 1 || true)
        if [[ -z "$SC_TOKEN" ]]; then
            SC_TOKEN=$(openssl rand -hex 24 2>/dev/null || date +%s%N | sha256sum | cut -c1-48)
        fi
        log_info "Generated new random token"
    fi
fi

PORT="${SC_PORT:-$DEFAULT_PORT}"

# --- Install binary ---
log_info "Installing ServerControl Agent v$AGENT_VERSION..."

BINARY_PATH="$INSTALL_DIR/$BINARY_NAME"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-}")" && pwd)"

if [[ -f "$SCRIPT_DIR/main.go" ]]; then
    # Running from inside the cloned repo — build directly
    if ! command -v go &>/dev/null; then
        log_error "Go toolchain not found. Install Go 1.21+ and retry."
        exit 1
    fi
    log_info "Building from local source at $SCRIPT_DIR..."
    cd "$SCRIPT_DIR"
    go build -ldflags="-s -w" -o "$BINARY_PATH" .
else
    # Running via remote pipe — clone repo and build
    TMP_BUILD=$(mktemp -d)
    trap "rm -rf '$TMP_BUILD'" EXIT

    if command -v go &>/dev/null; then
        log_info "Cloning source from GitHub and building..."
        if command -v git &>/dev/null; then
            git clone --depth 1 "https://github.com/$GITHUB_REPO.git" "$TMP_BUILD/src" 2>&1
        else
            log_error "git not found. Please install git and retry."
            exit 1
        fi
        cd "$TMP_BUILD/src/agent"
        go build -ldflags="-s -w" -o "$BINARY_PATH" .
    elif [[ -n "$GOARCH" ]]; then
        # Fallback: try pre-built binary from GitHub Releases
        DOWNLOAD_URL="https://github.com/$GITHUB_REPO/releases/download/v$AGENT_VERSION/servercontrol-agent-linux-$GOARCH"
        log_info "Go not found. Downloading pre-built binary from $DOWNLOAD_URL..."
        if ! curl -fsSL "$DOWNLOAD_URL" -o "$BINARY_PATH" 2>/dev/null; then
            log_error "Download failed. Install Go 1.21+ or provide a pre-built binary at $BINARY_PATH"
            exit 1
        fi
    else
        log_error "Cannot install: Go not found and architecture not recognised."
        exit 1
    fi
fi

chmod +x "$BINARY_PATH"
log_info "Binary installed at $BINARY_PATH"

# --- Create config directory and file ---
mkdir -p "$CONFIG_DIR"
chmod 750 "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
    log_warn "Backing up existing config to $CONFIG_FILE.bak"
    cp "$CONFIG_FILE" "$CONFIG_FILE.bak"
fi

cat > "$CONFIG_FILE" <<EOF
# ServerControl Agent Configuration
# Generated by install.sh on $(date)

PORT=$PORT
TOKEN=$SC_TOKEN
LOG_LEVEL=info
# TLS_CERT=/etc/servercontrol/cert.pem
# TLS_KEY=/etc/servercontrol/key.pem
EOF
chmod 640 "$CONFIG_FILE"
log_info "Config written to $CONFIG_FILE"

# --- Install systemd service ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-}")" && pwd)"
if [[ -f "$SCRIPT_DIR/servercontrol.service" ]]; then
    cp "$SCRIPT_DIR/servercontrol.service" "$SERVICE_FILE"
else
    cat > "$SERVICE_FILE" <<'UNIT'
[Unit]
Description=ServerControl Agent Daemon
After=network.target

[Service]
Type=simple
User=root
EnvironmentFile=/etc/servercontrol/agent.conf
ExecStart=/usr/local/bin/servercontrol-agent
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=servercontrol-agent

[Install]
WantedBy=multi-user.target
UNIT
fi

chmod 644 "$SERVICE_FILE"

# --- Enable and start service ---
if command -v systemctl &>/dev/null; then
    systemctl daemon-reload
    systemctl enable servercontrol
    systemctl restart servercontrol
    sleep 1
    if systemctl is-active --quiet servercontrol; then
        log_info "Service started successfully"
    else
        log_warn "Service may not have started. Check: journalctl -u servercontrol -n 20"
    fi
else
    log_warn "systemd not found. Start manually: $BINARY_PATH --token=$SC_TOKEN --port=$PORT"
fi

# --- Summary ---
echo ""
echo "============================================================"
echo "  ServerControl Agent installed successfully!"
echo "============================================================"
echo ""
echo "  Port  : $PORT"
echo ""
echo "  Token: $SC_TOKEN"
echo ""
echo "  To check status: systemctl status servercontrol"
echo "  To view logs:    journalctl -u servercontrol -f"
echo "============================================================"
echo ""
